### ISSUE TITLE
Error when using Ubuntu ARPG install script

### ISSUE THREAD

**Issue by apaulsonNTIA** [Algomorph/UbuntuARPGinstall#1]
Hiya algomorph,

I've been trying to use the script you wrote for the CU-ARPG coredev software and I ran into the following errors:

> Annas-MacBook-Air:Applications apaulson$ brew tap arpg/coredev
> ==> Tapping arpg/coredev
> Cloning into '/usr/local/Homebrew/Library/Taps/arpg/homebrew-coredev'...
> remote: Counting objects: 16, done.
> remote: Compressing objects: 100% (16/16), done.
> remote: Total 16 (delta 9), reused 7 (delta 0), pack-reused 0
> Unpacking objects: 100% (16/16), done.
> Checking connectivity... done.
> Error: Invalid formula: /usr/local/Homebrew/Library/Taps/arpg/homebrew-coredev/bullet.rb
> Calling Formula.sha1 is disabled!
> Use Formula.sha256 instead.
> /usr/local/Homebrew/Library/Taps/arpg/homebrew-coredev/bullet.rb:6:in `<class:Bullet>'
> Please report this to the arpg/coredev tap!
> Error: Invalid formula: /usr/local/Homebrew/Library/Taps/arpg/homebrew-coredev/zmqpp.rb
> Calling Formula.sha1 is disabled!
> Use Formula.sha256 instead.
> /usr/local/Homebrew/Library/Taps/arpg/homebrew-coredev/zmqpp.rb:8:in `<class:Zmqpp>'
> Please report this to the arpg/coredev tap!
> Error: Cannot tap arpg/coredev: invalid syntax in tap!

Any ideas?

**Comment by Algomorph** [comment]
Hi, @apaulsonNTIA , I've never tested the script on MacOS, but this looks like an error with the Bullet physics library. I can only say that at some point I have had trouble with ARPG using some older version of Bullet than was installed on my system, and solved it by simply disabling Bullet support in the CMake for whichever ARPG thing it was (can't remember).

I'm not really actively maintaining this script, since it relies on checkinstall/make install commands, whereas the proper solution would be to equip all ARPG things with CPack usage in their CMake scripts... If you figure out how to solve it and fix the script to be robust for this particular situation on Mac OS, I welcome the PR.
